services:
  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411:9411'
  springboot-app:
    image: 'device-management:latest' # Replace with your actual Spring Boot app image name
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase'
      - 'SPRING_DATASOURCE_USERNAME=myuser'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
      - 'SPRING_ZIPKIN_BASE_URL=http://zipkin:9411'
    ports:
      - '8080:8080'
    depends_on:
      - zipkin
